name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
    
    - name: Increment Patch Version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        VERSION_PARTS=(${VERSION//./ })
        PATCH_VERSION=$((${VERSION_PARTS[2]} + 1))
        NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH_VERSION"
        mvn versions:set -DnewVersion=$NEW_VERSION
    
    - name: Compile and Package
      run: mvn clean compile package
    
    - name: Build Docker image
      run: |
        DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
        JAR_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        docker build --build-arg JAR_VERSION=$JAR_VERSION -t shaharrel/maven-hello-world-shahar .
    
    - name: Tag Docker image
      run: |
        JAR_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        docker tag shaharrel/maven-hello-world-shahar shaharrel/maven-hello-world-shahar:$JAR_VERSION
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.WORKFLOW_USERNAME }}
        password: ${{ secrets.WORKFLOW_SECRET }}
    
    - name: Push Docker image to Docker Hub
      run: |
        JAR_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        docker push shaharrel/maven-hello-world-shahar:$JAR_VERSION
    
    - name: Download and Run Docker image
      run: |
        JAR_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        docker pull shaharrel/maven-hello-world-shahar:$JAR_VERSION
        # Add steps to run the downloaded Docker image (e.g., docker run)
