name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      

    - name: Increase jar Patch version
      run: |
        cd myapp
        current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo $current_version
        new_version=$(awk -F'.' '{$3=$3+1; OFS="."; print $1,$2,$3}' <<< "$current_version")
        echo $new_version
        mvn versions:set -DnewVersion=$new_version
        echo "NEW_VERSION=$new_version" >> $GITHUB_ENV


    - name: Compile code
      run: |
        cd myapp
        mvn compile

    - name: Package artifact
      run: |
        cd myapp
        mvn package

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp-artifact
        path: 'myapp/target/myapp-$NEW_VERSION.jar'

    - name: Debug new version
      run: |
        echo "New version: $NEW_VERSION"
    
    - name: Build Docker image
      run: |
        cd myapp
        docker build -t myapp:$NEW_VERSION --build-arg NEW_VERSION=$NEW_VERSION -f ../Dockerfile .

    - name: Tag Docker image
      run: docker tag myapp:$NEW_VERSION myapp:$NEW_VERSION
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.WORKFLOW_USERNAME }}
        password: ${{ secrets.WORKFLOW_SECRET }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push myapp:$NEW_VERSION

    - name: Download and run Docker image
      run: |
        docker pull myapp:$NEW_VERSION
        docker run --rm myapp:$NEW_VERSION