name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      

    - name: Increase jar Patch version
      run: |
        cd myapp
        new_version=$(awk -F'.' '/<artifactId>maven-jar-plugin<\/artifactId>/ {getline; gsub(/[<>]/,"",$1); split($1,a,"."); a[3]=a[3]+1; print a[1]"."a[2]"."a[3]}' pom.xml)
        sed -i.bak "s|\(<artifactId>maven-jar-plugin<\/artifactId>\)\(.*\)<version>.*<\/version>|\1\2<version>$new_version<\/version>|g" pom.xml


    - name: Compile code
      run: |
        cd myapp
        mvn compile

    - name: Package artifact
      run: |
        cd myapp
        mvn package

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp-artifact
        path: myapp/target/myapp.jar

    - name: Build Docker image
      run: |
        cd myapp
        docker build -t myapp:$version -f ../Dockerfile .

    - name: Tag Docker image
      run: docker tag myapp:$version myapp:$version

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.WORKFLOW_USERNAME }}
        password: ${{ secrets.WORKFLOW_SECRET }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push myapp:$version

    - name: Download and run Docker image
      run: |
        docker pull myapp:$version
        docker run --rm myapp:$version
